spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    host: localhost
    listener:
      type: SIMPLE

demo:
  appnameAndLeadingCharacterCount:
    - appname: hoge
      leadingCharacterCount: 1
    - appname: default
      leadingCharacterCount: 2
